---
title: "Ejercicios"
subtitle: "Ecuaciones y Sistemas Lineales"
author: "Curso Álgebra Lineal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Pregunta 1

Estudia la compatibilidad de los siguientes sistemas y resuélvelos cuando sea posible

$$(a)\left\{\begin{matrix}
x & + & y &+ & 2z & = & 0\\
x & + & 2y &+ & z & = & 1\\
2x & + & 2y &+ & z & = & -1
\end{matrix}\right.$$

$$(b)\left\{\begin{matrix}
x & - & 2y &+ & 2z &+&3t& = & -1\\
x & - & 2y & + & z &+&3t& = & -4\\
-x & + & 2y && &+&2t& = & -3\\
x & - & 2y & + & 2z &+&5t& = & -5
\end{matrix}\right.$$

$$(c)\left\{\begin{matrix}
x & + & y & + & z & + & 2t & = & -1\\
2x & + & y & + & z & + & 4t & = & -3\\
3x &  &  & + & 2z & + & 4t & = & -6
\end{matrix}\right.$$

$$(d)\left\{\begin{matrix}
x & + & 2y &  &  & - & 3t & = & 3\\
3x & - & y & - & 7z & - & 9t & = & 2\\
-x & + & 2y & + & 4z & +  & 3t & = & 1
\end{matrix}\right.$$

$$(e)\left\{\begin{matrix}
x & - & 3y & + & 3z & = & 1\\
3x & - & 9y & + & 2z & = & 10
\end{matrix}\right.$$

$$(f)\left\{\begin{matrix}
x & + & 2y & + & z & + & 2t & + & 4u & = & 4\\
-2x & - & 4y & - & z & - & 3t & - & 6u & = & 6\\
2x & + & 4y &  &  & + & 2t & + & 4u & = & 4\\
3x & + & 6y & + & z & + & 4t & + & 7u & = & 8\\
\end{matrix}\right.$$



## Pregunta 2

Encuentra todas las matrices $A\in\mathcal{M}_2(\mathbb{R})$ tales que sean idempotentes, es decir, que cumplan $A^2 = A$

## Pregunta 3

Sea $A\in\mathcal{M}_n(\mathbb{R})$. Demuestra que $A$ es idempontente si, y solo si, la matriz $B = 2A-I_n$ es involutiva (si cumple $B^2=I_n$)

## Pregunta 4

Demostrad que si $a,b,c,d\in\mathbb{R}$ son estrictamente positivos, entonces el sistema $$\left\{\begin{matrix}
x & + & y & + & z & + & t & = & a\\
x & - & y & - & z & + & t & = & b\\
-x & - & y & + & z & + & t & = & c\\
-3x & + & y & - & 3z & - & 7t & = & d
\end{matrix}\right.$$ no tiene solución

## Pregunta 5

¿Para qué valores de $\alpha,\beta\in\mathbb{R}$ tiene solución el sistema?

$$\left\{\begin{matrix}
x & + & by & + & az & = & 1\\
ax & + & by & + & z & = & a\\
x & + & aby & + z & = & b
\end{matrix}\right.$$

Resolvedlo y determinad cuando tiene una solución única.

## Pregunta 6

Resolved el sistema de ecuaciones lineales complejas

$$\left\{\begin{matrix}
x & + & y & + & iz & + & t & = & 0\\
2x & - & y & + & 2z & - & t & = & 1\\
x & + & iy & - & z & + & it & = & 2\\
x & + & y & + & z & - & t & = & 0
\end{matrix}\right.$$

## Pregunta 7

Demostrad que el sistema siguiente no tiene solución+

$$\left\{\begin{matrix}
x & + & 2y & & & + & 3t & = & 1\\
x & + & 2y & + & 3z & + & 3t & = & 3\\
x &  &  & + & z & + & 2t & = & 3\\
x & + & y & + & z & + & 2t & = & 1\\
\end{matrix}\right.$$

## Pregunta 8

**Esta pregunta es para cuando hayas completado la sección de Sistemas con `R`, `Python` y `Octave`**

Crear un programa en `R`, `Python` y `Octave` que calcule ecuaciones matriciales para matrices de cualquier orden.

El usuario deberá introducir el orden de las matrices, $n$, y las matrices $A,B$ tales que $AX = B$.

Por su parte, el programa deberá comprobar si las matrices introducidas por el usuario son del orden adecuado y, en caso afirmativo, realizar las operaciones necesarias para calcular $X$.

El programa deberá devolver por consola la matriz $X$ junto con un mensaje de que todo ha salido correcto. En caso de no ser así, deberá indicar por consola que ha habido un error (y a ser posible, el tipo de error).
