---
title: "Tema 10 - Demostraciones"
author: "María Santos"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

**Proposición.** Sea $f$ una forma bilineal (sesquilineal) con matriz $G$ en una base $\{e_1,\dots,e_n\}$. Sean $G_r$ los menores principales de orden $r$ (las submatrices de $G$ formadas por las primeras $r$ filas y las primeras $r$ columnas con $r = 1,\dots,n$). Entonces, $f$ es un producto escalar si, y solo si $G$ es simétrica (hermítica) y $\det(G_r)>0$ $\forall r = 1,\dots,n$

**Demostración**

Denotemos por $E_r$ el subespacio $\langle e_1,\dots,e_r\rangle$ y por $f_r$ la restricción de $f$ a $E_r\times E_r$, con lo cual

$$\begin{matrix}
f & E_r\times E_r & \longrightarrow & \mathbb{R} (\text{o }\mathbb{C})\\
 & (u,x) & \mapsto & f(u,x)
\end{matrix}$$

La matriz de $f_r$ en la base $\{e_1,\dots,e_r\}$ no es otra que $G_r$.

Supongamos que $f$ es un producto escalar en $E$. Entonces, $f_r$ es un producto escalar en $E_r$  y por el `Teorema de Ortogonalización de Gram-Schmidt` existe una base ortonormal de $E_r$.

Si tenemos que $P$ es la matriz del cambio de base de $\{e_1,\dots,e_r\}$ a la base ortonormal $\{u_1,\dots,u_r\}$, tendremos que $$I = P^tG_r\bar{P}$$ de donde

$$\det(I) = 1 = \det(P^tG_r\bar{P}) = \det(P^t)\det(G_r)\det(\bar{P}) = \det(G_r)\det(P)^2$$

Con lo cual, $$\det(G_r)\det(P)^2 = 1\Leftrightarrow \det(G_r) = \frac{1}{\det{P}^2}>0$$

Así ya tenemos que $\det(G_r)>0$

Supongamos ahora que $\det(G_r)>0$ para todo $r$ y vayamos a construir una base $u_1,\dots,u_r$ tal que $f(u_i,u_j) = 0$ si $i\ne j$ y $f(u_i,u_i) = 1$. Entonces, de esta forma, la matriz asociada a $f$ será la matriz identidad $I$, con lo cual sabemos que $f$ será un producto escalar.

Para construir la base ortonormal anterior, haremos uso del método de ortonormalización de Gram-Schmidt:

- $f(e_1,e_1) = g_{11} = \det(G_1)>0$. Por tanto, existe $\sqrt{\langle e_1,e_1\rangle}$ y podemos así construir el primer vector de la base: $$u_1 = \frac{e_1}{\sqrt{\langle e_1,e_1\rangle}}$$ que es un vector unitario y es base de $E_1 = \langle e_1\rangle = \langle u_1\rangle$
- Supongamos ahora que $u_1,\dots,u_r$ es una base de $E_r$ tal que $f(u_i,u_j) = 0$ si $i\ne j$ y $f(u_i,u_i)=1$. Construimos el vector $u'_{r+1} = e_{r+1}-(k_1u_1+\cdots+k_ru_r)$ con $k_i = f(e_{r+1},u_i)$. Este vector es ortogonal a cada uno de los vectores $u_1,\dots,u_r$. Si ahora demostrásemos que $f(u'_{r+1},u'_{r+1})>0$, entonces el vector unitario $$u_{r+1} = \frac{u'_{r+1}}{\sqrt{f(u'_{r+1},u'_{r+1})}}$$ será tal que $u_1,\dots,u_r,u_{r+1}$ formará una base ortonormal de $E_{r+1}$. Calculemos pues $$f(u'_{r+1},u'_{r+1}) = f(e_{r+1},e_{r+1})-f\left(e_{r+1},\sum_{i = 1}^rk_iu_i\right)-f\left(\sum_{i = 1}^rk_iu_i, e_{r+1}\right)+f\left(\sum_{i=1}^rk_iu_i,\sum_{i=1}^rk_iu_i\right)$$ $$ = f(e_{r+1},e_{r+1})-\sum_{i = 1}^r\bar{k_i}f(e_{r+1},u_i)-\sum_{i = 1}^rk_if(u_i,e_{r+1})+\sum_{i = 1}^rk_i\bar{k_i}$$ $$ = f(e_{r+1},e_{r+1})-\sum_{i = 1}^r\overline{f(e_{r+1},u_i)}f(e_{r+1},u_i)-\sum_{i = 1}^rf(e_{r+1},u_i)f(u_i,e_{r+1})+\sum_{i = 1}^rf(e_{r+1},u_i)\overline{f(e_{r+1},u_i)}$$ $$=f(e_{r+1},e_{r+1})-\sum_{i = 1}^rf(e_{r+1},u_i)f(u_i,e_{r+1}) = \begin{vmatrix}1 & \cdots &  0 & f(u_1,e_{r+1})\\ \vdots & \ddots & \vdots & \vdots\\ 0 & \cdots & 1 & f(u_r,e_{r+1})\\ f(e_{r+1},u_1) & \cdots & f(e_{r+1},u_r) & f(e_{r+1},e_{r+1})\end{vmatrix}$$

La matriz que aparece aquí es la matriz de $f_{r+1}$ en la base $u_1,\dots,u_r,e_{r+1}$ y se obtiene, por tanto, de la matriz $G_r$ por un cambio de base.

Es entonces de la forma $P^tG_{r+1}\bar{P}$ y su determinante es $\det(G_{r+1})\det(P)^2>0$ por ser $\det(G_{r+1})>0$ por hipótesis.

Queda así finalizada la demostración.