---
title: "Tema 10 - Cadenas de Markov"
author: Juan Gabriel Gomila & María Santos
date: 
output: 
  ioslides_presentation:
    widescreen: true
    css: Mery_style.css
    logo: Images/matriz_mov.gif
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, engine.path = list(
  octave = '/Applications/Octave-4.4.1.app/Contents/Resources/usr/bin/octave'
))
library(reticulate)
library(matlib)
use_python("/anaconda3/bin/python3")
```

# Introducción

## Introducción

El <l class = "definition">análisis de colas</l> es una de las herramientas más importantes para estudiar sistemas de comunicación.

<div class = "example">
**Ejemplo 1**

Ejemplo de colas

- Número de pacientes en una lista de espera
- Número de documentos en lista de espera de una impresora
</div>

## Introducción

En teoría de colas tendremos dos protagonistas: los clientes y los servidores

El tamaño de la cola será el número de clientes que esperan ser servidos

El objetivo de la teoría de colas es predecir el rendimiento de la cola

<div class = "example">
**Ejemplo 2**

Ejemplo de predicciones

- Número de clientes atendidos por unidad de tiempo
- Espera media de un cliente antes de ser servido
- Tamaño de la cola
</div>

## Introducción

Supondremos que el tiempo es discreto o medido en unidades de tiempo discretas de tamaño finito.

Por lo tanto, podremos tener múltiples llegadas o múltiples salidas por unidad de tiempo.

## Introducción

Estudiaremos distintos tipos de colas, caracterizadas por

- El número total de clientes en el sistema
- El número máximo de clientes que pueden llegar por unidad de tiempo
- La distribución de las llegadas de los clientes
- El número de servidores del sistema
- La disciplina de la cola que decide la política de qué clientes son servidos primero
- El tamaño de la cola

# La notación de Kendall

## La notación de Kendall

La <l class = "definition">notación de Kendall</l> nos sirve para describir una cola.

Una cola se representa por $A/B/c/n/p$ donde

- $A:$ estadísticas de las llegadas
- $B:$ estadísticas de las salidas
- $c:$ número de servidores
- $n:$ tamaño de la cola
- $p:$ tamaño de la población de clientes

Los dos últimos campos son opcionales y se supone que son infinitos en el caso de no ponerlos.

## La notación de Kendall

Los campos $A$ y $B$ pueden ser de diferentes tipos

- Deterministas, $D$: las llegadas o las salidas tienen una tasa fija de llegada o salida
- Markovianos, $M$: las llegadas o las salidas siguen una distribución de Poisson
- Generales, $G$: Las llegadas o las salidas tienen una distribución general

## La notación de Kendall

<div class = "example">
**Ejemplo 3**

Una cola $M/M/1$ tendría 

- Llegadas y salidas con distribución binomial o de Poisson 
- En cada unidad de tiempo puede llegar como máximo un cliente y puede irse como máximo un cliente 
- Tamaño infinito
- Población de los clientes es también infinita
</div>

<div class = "example">
**Ejemplo 4**

Una cola $M/M/1/B$ tendría 

- Llegadas y salidas con distribución binomial o de Poisson 
- En cada unidad de tiempo puede llegar como máximo un cliente y puede irse como máximo un cliente 
- Tamaño $B$
- Población de los clientes es también infinita
</div>

## La notación de Kendall

<div class = "example">
**Ejemplo 5**

Una cola $M/M/J/B$ tendría 

- Llegadas y salidas con distribución binomial o de Poisson 
- En cada unidad de tiempo puede llegar como máximo un cliente y puede irse como máximo un cliente de los $J$ servidores disponibles
- Tamaño $B$
- Población de los clientes es también infinita
</div>

<div class = "example">
**Ejemplo 6**

Una cola $M^m/M/1/B$ tendría 

- Llegadas y salidas con distribución binomial o de Poisson 
- En cada unidad de tiempo pueden llegar como máximo $m$ clientes y pueden irse como máximo un cliente, ya que solo hay un servidor
- Tamaño $B$
- Población de los clientes es también infinita
</div>

## La notación de Kendall

<div class = "example">
**Ejemplo 7**

Una cola $M/M^m/1/B$ tendría 

- Llegadas y salidas con distribución binomial o de Poisson 
- En cada unidad de tiempo puede llegar como máximo un cliente y pueden irse como máximo $m$ clientes
- Tamaño $B$
- Población de los clientes es también infinita
</div>

## La notación de Kendall

Las colas que trataremos serán de lis siguientes tipos

- $M/M/1$. Llegadas de un cliente por unidad de tiempo, salidas de un cliente por unidad de tiempo y tamaño infinito. La matriz de transición $P$ será tridiagonal
- $M/M/1/B$. Llegadas de un cliente por unidad de tiempo, salidas de un cliente por unidad de tiempo y tamaño finito $B$. La matriz de transición $P$ será tridiagonal
- $M^m/M/1/B$. Llegadas múltiples por unidad de tiempo, salidas de un cliente por unidad de tiempo y tamaño finito. La matriz de transición $P$ será Hessenberg inferior
- $M/M^m/1/B$. Llegadas de un cliente por unidad de tiempo, múltiples salidas por unidad de tiempo y tamaño finito $B$. La matriz de la transición $P$ será Hessenberg superior 

# Rendimiento de la cola
## Rendimiento de la cola

<l class = "definition">Rendimiento de la cola.</l> Tasa de clientes que abandonan la cola por unidad de tiempo. Lo denotaremos $Th$. Se expresará en clientes o paquetes por unidad de tiempo

También se le denomina <l class = "definition">tráfico medio de salida</l>, $N_a$(out)

# Eficiencia 
## Eficiencia 

<l class = "definition">Eficiencia.</l> Nos da el tanto por 1 de clientes o paquetes transmitidos por unidad de tiempo en el sistema relativo al número total de clientes o paquetes que llegan por unidad de tiempo. Lo denotaremos $\eta$

$$\eta = \frac{N_a(\text{out})}{N_a(\text{in})}$$

donde $N_a(\text{in})$ representa el número de clientes o paquetes que llegan por unidad de tiempo y $N_a(\text{out})$, el número de clientes o paquetes que salen por unidad de tiempo

La eficiencia también es conocida como <l class = "definition">probabilidad de acceso</l>, $p_a=\eta$.

## Eficiencia 

Podemos escribir la eficiencia en función del rendimiento $Th$ como 

$$\eta = \frac{Th}{N_a(\text{in})}$$

Observemos que la eficiencia siempre será una cantidad menor que 1: $\eta\le 1$

## Eficiencia 

<div class = "example">
**Ejemplo 8**

Si en la cola salen 3 clientes por unidad de tiempo mientras llegan 5, el rendimiento será $Th=5$, mientras que la eficiencia será $$\eta = \frac{3}{5} = 0.6$$

</div>

# Conservación del tráfico

## Conservación del tráfico
Cuando una cola llega a su estado de equilibrio, los clientes que llegan tienen dos opciones:

- ser procesados por la cola
- perderse

Entonces, 
$$N_a(\text{in}) = N_a(\text{out})+N_a(\text{lost})$$
donde $N_a(\text{lost})$ es el número medio de clientes que se pierden por unidad de tiempo.

La ecuación anterior es válida en el estado de equilibrio. Dividiéndola entre $N_a(\text{in})$, resulta que

$$1 = \eta+L $$
donde $L$ es la probabilidad de pérdida de clientes: $L = 1-\eta$

# Colas $M/M/1$

## Colas $M/M/1$


