---
title: "Ejercicios"
subtitle: "Diagonalización"
author: "Curso Álgebra Lineal"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
```

## Pregunta 1

Santa Cruz del Islote es famosa por ser la isla con mayor densidad de población del mundo. Supongamos que el islote fue habitado por 20 colonos procedentes del continente. Además, un 60% de la població del islote es menor de edad. Debido a la dificultad geográfica, la población desciende de manera natural un 20% anual.

La actividad principal de la comunidad es la pesca. Se estima que a lo largo del año cada habitante mayor de edad del Islote pesaca, de media, 3050 sardinas. En ausencia de pesca, la tasa de crecimiento de las sardinas en aguas aledañas es de 220% cada año.

La actividad pesquera atrae a población del continente en función de la población de sardinas. Supongamos que el porcentaje de inmigrantes cada año es del 0.2% de la población de ejemplares del año anterior.

Consideramos que la población de sardinas en las aguas del islote es de 50000 ejemplares.

Sean $x_n$ el número de habitantes de Santa Cruz del Islote en el año $n$ tras la fundación de la comunidad e $y_n$ el número de sardinas en aguas aledañas al islote en el mismo año $n$

- Encuentra la matriz cuadrada $A$ de orden 2 tal que $$\begin{pmatrix}x_{n+1}\\ y_{n+1}\end{pmatrix} = A\begin{pmatrix}x_n\\ y_n\end{pmatrix}$$
- Encuentra las fórmulas explícitas para $x_n$ e $y_n$ en función de $n$ a partir de las condiciones iniciales dadas.

## Pregunta 2

Estudia la diagonalización de las matrices

$$\begin{pmatrix}4 & 1 & 0 & 1\\
2 & 3 & 0 & 1\\
-2 & 1 & 2 & -3\\
2 & -1 & 0 & 5\end{pmatrix}$$

$$\begin{pmatrix}-3 & -7 & -5\\
2 & 4 & 3\\
1 & 2 & 2\end{pmatrix}$$

$$\begin{pmatrix}
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1\\
0 & 0 & 0 & 1\end{pmatrix}$$

$$\begin{pmatrix}
2 & 1 & 0 & 0\\
0 & 2 & 3 & 0\\
0 & 0 & 2 & 0\\
0 & 0 & 0 & 2\end{pmatrix}$$

$$\begin{pmatrix}
4 & 0 & -2 & -2\\
-5 & 0 & -2 & 4\\
-3 & 0 & -1 & 3\\
1 & 0 & 1 & 1
\end{pmatrix}$$

$$\begin{pmatrix}
-4 & 1 & 1 & 1\\
1 & -6 & 2 & 1\\
1 & 2 & -5 & 1\\
1 & 1 & 1 & -4
\end{pmatrix}$$

## Pregunta 3

Justifica que las siguientes matrices son invertibles y, en cada caso, calcula su inversa

$$\begin{pmatrix}
2 & -1 & 3\\
4 & 1 & 6\\
1 & 5 & 3
\end{pmatrix}$$

$$\begin{pmatrix}
1 & 0 & 1 & 0\\
2 & -1 & 0 & 2\\
-1 & 0 & 0 & 1\\
4 & 1 & -1 & 0
\end{pmatrix}$$

$$\begin{pmatrix}
a & b & 0 & 0\\
0 & a & c & 0\\
0 & 0 & a & d\\
0 & 0 & 0 & a
\end{pmatrix}\qquad a,b,c,d\ne 0$$


## Pregunta 4

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
2a-b & 0 & 2a-2b\\
1 & a & 2\\
-a+b & 0 & -a+2b
\end{pmatrix}$$

según los valores de $a,b\in\mathbb{R}$. En el caso $a = 1,\ b = 2$ calcula una matriz $P$ de vectores propios y la matriz diagonal

## Pregunta 5

Considera la matriz

$$A = \begin{pmatrix}
1 & 1 & -2\\
-1 & 2 & 1\\
0 & 1 & -1
\end{pmatrix}$$

- Encuentra los valores propios de $A$
- Encuentra una matriz $P$ invertible tal que $P^{-1}AP$ sea una matriz diagonal
- Utiliza el apartado anterior para encontrar $A^{-1}$
- Calcula $A^8$


## Pregunta 6

Considera la matriz 

$$A =  \begin{pmatrix}
4 & -1 & 0\\
-1 & 5 & -1\\
0 & -1 & 4
\end{pmatrix}$$

- Encuentra los valores propios de $A$
- Encuentra una matriz $P$ invertible tal que $P^{-1}AP$ sea una matriz diagonal
- Utiliza el apartado anterior para encontrar $A^{-1}$
- Calcula $A^{21}$

## Pregunta 7

Utiliza la diagonalización de matrices para calcular, en cada caso, las potencias indicadas

- $A^5$ donde $$A = \begin{pmatrix}
4 & -6\\
3 & -5
\end{pmatrix}$$
- $B^{49}$ donde $$B =\begin{pmatrix}
11 & -6 & -12\\
13 & -6 & -16\\
5 & -3 & -5
\end{pmatrix}$$
- $C^{10}$ donde $$C = \begin{pmatrix}
7 & 9 & -12\\
10 & 16 & -22\\
8 & 12 & -16
\end{pmatrix}$$

## Pregunta 8

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
1 & 0 & 1 & b\\
0 & 1 & 1 & 1\\
0 & b & -1 & a^2\\
0 & 0 & 0 & 3
\end{pmatrix}$$

donde $a,b\in\mathbb{R}$

## Pregunta 9

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
a+3 & a & 0 & 0\\
-a & -a+3 & 0 & 0\\
a & a-1 & a+1 & a-1\\
-a & 1-a & 1-a & 3-a
\end{pmatrix}$$

donde $a,b\in\mathbb{R}$

## Pregunta 10

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
a+2 & 2a+4 & 0 & 2a\\
0 & -1 & 0 & -a-1\\
-2 & -a-3 & a & -a+1\\
0 & a+1 & 0 & 2a+1
\end{pmatrix}$$

donde $a\in\mathbb{R}$

## Pregunta 11

Resuelve el sistema

$$\left\{\begin{matrix}
x_{n+1} &=& 2x_n+6y_n\\
y_{n+1} &=& 6x_n-3y_n
\end{matrix}\right.$$

sabiendo que $x_1 = 0$ e $y_1 = -1$

## Pregunta 12

Considera la sucesión $\frac{1}{1},\frac{3}{2},\frac{7}{5},\dots,\frac{a_n}{b_n}$ donde $$a_{n+1} = a_n+2b_n\qquad b_{n+1} = a_n+b_n$$

- Encuentra una matriz $A$ tal que $$\begin{pmatrix}a_{n+1}\\ b_{n+1}\end{pmatrix} = A\begin{pmatrix}a_n\\b_n\end{pmatrix}$$
- Da la expresión de $a_n$ y $b_n$ y preuba que $\lim_{n\to\infty}\frac{a_n}{b_n} = \sqrt{2}$

## Pregunta 13

Sean $\{x_n\}, \{y_n\},\{z_n\}$ sucesiones de números reales definidas recursivamente por

$$\left\{\begin{matrix}
x_{n+1} & = & 3x_n-z_n\\
y_{n+1} & = & 8x_n -2y_n-4z_n\\
z_{n+1} & = & 2x_n
\end{matrix}\right.$$

para todo $n\ge 0$. Calcula los siguientes términos generales en función de $x_0,y_0,z_0$

## Pregunta 14

Encuentra un polinomio que se anule por la matriz

$$A = \begin{pmatrix}
2 & 3 & 3\\
-a & -1 & -2\\
a & 0 & 1
\end{pmatrix}$$

Estudia la diagonalización de la matriz anterior según los valores del parámetro $a\in\mathbb{R}$

## Pregunta 15

Estudia la diagonalización de las matrices de la forma

$$A = \begin{pmatrix}
0 & a & 0\\
0 & b & 0\\
c & 0 & d
\end{pmatrix}$$

según los valores de $a,b,c,d\in\mathbb{R}$. Da una matriz $P$ de vectores propios y la matriz diagonal cuando $a = 1,b = d  = 2, c = 0$

## Pregunta 16

Demuestra que la matriz 

$$A = \begin{pmatrix}
0 & 0 & a\\
0 & b & 0\\
c & 0 & 0
\end{pmatrix}$$

es diagonalizable en el caso en que $ac>0$ y $b = \sqrt{ac}$

## Pregunta 17

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
1 & a & 1\\
0 & 1 & b\\
0 & 0 & c
\end{pmatrix}$$

según los valores de $a,b,c\in\mathbb{R}$

## Pregunta 18

Estudia la diagonalización de las matrices de la forma

$$A = \begin{pmatrix}
1 & a & b & c\\
0 & 2 & d & e\\
0 & 0 & 2 & f\\
0 & 0 & 0 & 2
\end{pmatrix}$$

según los valores de $a,b,c,d,e,f\in\mathbb{R}$

## Pregunta 19

Sea $m\ne 0$ y 

$$A = \begin{pmatrix}
0 & m & m^2\\
\frac{1}{m} & 0 & m\\
\frac{1}{m^2} & \frac{1}{m} & 0
\end{pmatrix}$$

Prueba que existen $a,b\in\mathbb{R}$ tales que $(A-aI_3)(A-bI_3) = 0$. ¿Qué se deduce de $a$ y $b$ con respecto a la matriz $A$?

## Pregunta 20

Sea $A\in\mathcal{M}_n(\mathbb{R})$ con $A\ne 0,I_n$ una matriz tal que $A^2 = A$. Calcula sus valores propios.

Encuentra una matriz de orden 2 que satisfaga las condiciones anteriores. Prueba que la matriz $A$ encontrada anteriormente es diagonalizable y calcula $A^{20}$

## Pregunta 21

Estudia la diagonalización de la matriz

$$A = \begin{pmatrix}
1 & 2 & 1\\
2 & 0 & 1\\
0 & 0 & 1
\end{pmatrix}$$

Da, si es posible, una matriz $P$ de valores propios y la matriz diagonal. Justifica que $A$ es invertible y da la expresión de $A^{-1}$
